# Generated by Django 4.1.2 on 2022-12-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_brand_product_category_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
